- README.md
- bin/npq-hero.js
fix(packageManager): simplify other package manager specifying through env variables
> fix(packageManager): simplify package manager specifying

- __tests__/marshalls.base.test.js
- lib/cli.js
- lib/marshall.js
- lib/marshalls/author.marshall.js
- lib/marshalls/baseMarshall.js
- lib/marshalls/scripts.marshall.js
- lib/marshalls/snyk.marshall.js
- package.json
- yarn.lock
> Lint Party  🎉💃🕺🍾

- __tests__/packageRepoUtils.test.js
- lib/helpers/packageRepoUtils.js
- package.json
Implementation of enhancement requested in issue [#45](https://github.com/lirantal/npq/issues/45) .
> Add caching for package info calls

- __tests__/marshalls.repo.test.js
- __tests__/packageRepoUtils.test.js
- bin/npq.js
- lib/helpers/packageRepoUtils.js
- lib/marshalls/repo.marshall.js
- package.json
- yarn.lock
Added repo checking, as mentioned in issue #22
> Add repo identification

- __tests__/marshalls.tasks.test.js
Fixes async test which isn't properly checking for promise fullfillment
> tests(marshalls.tasks): fix async test handling

- lib/helpers/cliSupportHandler.js
- package.json
- yarn.lock
Proposed change:
- Add update-notifier that will show when a new release is out
- Fix the HUSKY params (@gagyibenedek will be great if you can test this on Windows, it should work according to the issue about it on husky)
Looks like this:
> feat(update-notifier): add update-notifier to prompt on new releases

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
- CODE_OF_CONDUCT.md
- package.json
- yarn.lock
🎉 npq now passes all the open source checks!!
Continuation PR from: https://github.com/lirantal/npq/pull/54 by the wonderful @gautamarora ;-)
@lirantal @gagyibenedek - can you review the docs that i've added.
> Add Open Source Check

- README.md
With `npm audit` out, I get this question a lot of why is NPQ different from `npm audit`.
Would be great if you find other differentiators which we can list down, or anything else we can add to the FAQ to make it clear.
> Adding a FAQ section to the docs

- lib/marshall.js
- lib/packageManager.js
- package.json
- yarn.lock
We kept npq to be compatible with older npm versions (>=6) so it can be easily adopted by users without enforcing them to use latest features (async/await, etc)
1. Remove object.entires
2. Remove async definitions
3. Adds lints to ensure this doesn't happen again
> fix(npm-versions): compatible with >= 6.0.0

- package.json
- yarn.lock
Updating out of sync yarn.lock file
#74 #75
> Fix/lockfile out of date 

- README.md
Fixes #89 
Updates some assertions that are not up to date anymore.
Fixes #89
> fix(README): update outdated faq comparison

- __tests__/packageManager.test.js
- bin/npq.js
- lib/packageManager.js
- yarn.lock
Refactored the packageManager code so that we don't need to actually pass each package but rather just pass away the relevant process.argv elements.
Fixes #99
Tests have been updated to accommodate refactoring
> fix(packagemanager): spawned without extra command arguments

- README.md
Fixes #110
People looking at this project for the first time may not trust it, because the grammar and spelling in the readme document do not make sense. This PR was created to correct that. The only change is to README.md, and only to fix the aforementioned grammar and spelling.
This doesn't affect code - only documentation, so the tests are also unaffected, and no new tests need to be added.
- **N/A** I have added tests to cover my changes. (no code changes, only documentation changes; therefore, no new tests are needed, or edits needed to existing tests)
> Improve grammar and fix typos in README.md

- lib/marshalls/snyk.marshall.js
Snyk API request the latest version to be provided instead of the `latest` tag so this PR resolves it for it.
> fix(snyk): resolve latest version for api request

- lib/helpers/packageRepoUtils.js
- lib/marshalls/index.js
use cached requests to npm registry to resolve
version information and readme content. also,
use listr in concurrent mode to run all the
promises in parallel.
> fix(performane): use cache and concurrent

- lib/marshalls/snyk.marshall.js
If users don't have a token, use the minimal test endpoint to provide results about vulnerabilities
> feat: use snyk test endpoint for packages

- .travis.yml
> build: ignore scripts due to own postinstall

- __tests__/scripts.test.js
Use platform-agnostic temporary file in tests for install scripts.
Related to PR #150 / issue #90 
Tests should work on all platforms!
I've verified that with this change, all tests pass on both Linux and Windows 10.
> test(install scripts): make install script tests cross-platform

- README.md
Uses the package health badge for an overall of the package from [Snyk Advisor](https://snyk.io/advisor/npm-package/npq)
Provide more context to users for the overall package status.
> fix: update README badges to use package health score

- .github/workflows/main.yml
Moving the if conditional to job level instead of step level will eliminate unnecessary executions of release job in many cases.
- [x ] New feature (non-breaking change which adds functionality)
I made a similar change to lockfile-lint and since I made this enhancement there, I thought I will create it here too
It probably works
- [] I have added tests to cover my changes.
- [x ] All new and existing tests passed.
> ci: move release if conditional from step to job level

- lib/marshalls/snyk.marshall.js
* Replace `https://snyk.io/api/v1/test/npm` API with `https://snyk.io/api/v1/vuln/npm` (like Snyk CLI)
https://github.com/lirantal/npq/issues/183
> fix: issue #183

- lib/cliCommons.js
Parse both name and version from CLI
https://github.com/lirantal/npq/issues/188
> fix: issue 188

- README.md
https://github.com/lirantal/npq/issues/214
Fixes #214
> Added instructions for dry-run

- lib/cliCommons.js
> fix: package fetch spec resolves to latest instead of wildcard asterisk

- lib/marshalls/age.marshall.js
> fix: dont break on undefined variable due to package not existing

- lib/cliCommons.js
> feat: support npm install aliases to be compatible with commands

- .github/workflows/main.yml
- package.json
Move from `master` to `main` branch conventions
> build: update named branch from master to main

- __tests__/marshalls.base.test.js
- __tests__/packageManager.test.js
> style: fix spelling

- bin/npq-hero.js
Small fix that probably came in from prior refactoring
> fix: remove extra function argument

- lib/helpers/packageRepoUtils.js
> fix: string's replace() function does just one occurrence replace

- package.json
- yarn.lock
> fix: upgrade dependencies to remove security vulnerabilities

- package.json
- yarn.lock
Update semantic-release version
> build: update semantic-release dep

- package.json
Add package provenance attestation as part of publishing the package.
> chore: update provenance entry

- lib/marshalls/baseMarshall.js
Refactor here.
https://github.com/lirantal/npq/blob/e1cb2aa25d975798b235351450f4267d8eb472d6/lib/marshalls/baseMarshall.js#L40-L53
Improve readability.
> Refactor `setMessage` arguments in `baseMarshall.js`

- __tests__/__fixtures__/test.marshall.js
- __tests__/marshalls.tasks.test.js
- lib/cliCommons.js
- lib/helpers/packageRepoUtils.js
- lib/marshall.js
- lib/marshalls/age.marshall.js
- lib/marshalls/author.marshall.js
- lib/marshalls/baseMarshall.js
- lib/marshalls/downloads.marshall.js
- lib/marshalls/expiredDomains.marshall.js
- lib/marshalls/index.js
- lib/marshalls/license.marshall.js
- lib/marshalls/readme.marshall.js
- lib/marshalls/repo.marshall.js
- lib/marshalls/scripts.marshall.js
- lib/marshalls/snyk.marshall.js
- lib/packageManager.js
> chore: format files

- lib/marshalls/signatures.marshall.js
- package.json
- yarn.lock
Fixes #278
This is related work to package provenance and attestations verification and is only scoped to the signed registry pakument.
> feat: new marshall to compare pakument signatures with repository keys

- lib/marshalls/provenance.marshall.js
Adds support to ensure the package provenance exists
Fixes #275
> feat: introduce new provenance marshall

- __tests__/marshalls.signatures.test.js
- lib/marshalls/provenance.marshall.js
- lib/marshalls/signatures.marshall.js
> fix: use node-fetch for older runtime versions

- __tests__/marshalls.provenance.test.js
> test: add test cases for the provenance marshall

- __tests__/marshalls.provenance.test.js
- lib/marshalls/provenance.marshall.js
> fix: provenance will throw a warning for missing package attestations

- lib/marshalls/age.marshall.js
- lib/marshalls/author.marshall.js
- lib/marshalls/baseMarshall.js
- lib/marshalls/constants.js
- lib/marshalls/downloads.marshall.js
- lib/marshalls/expiredDomains.marshall.js
- lib/marshalls/index.js
- lib/marshalls/license.marshall.js
- lib/marshalls/provenance.marshall.js
- lib/marshalls/readme.marshall.js
- lib/marshalls/repo.marshall.js
- lib/marshalls/scripts.marshall.js
- lib/marshalls/signatures.marshall.js
- lib/marshalls/snyk.marshall.js
> feat: split marshalls by categories

- lib/marshalls/typosquatting.marshall.js
- package-lock.json
- package.json
Add new Typosquatting detection marshall
> feat: introduce new typosquatting marshall

- lib/marshalls/snyk.marshall.js
> fix: error wording on vulnerable paths found

- .github/workflows/main.yml
* specify permissions
* enable colors
* update actions
* enable npm cache
* do not run coverage or publish from forks
* do not fail fast
Test run from my fork https://github.com/XhmikosR/npq/actions/runs/16701631970/job/47273619406
___
Other
___
- Update GitHub Actions workflow configuration
- Add security and performance improvements
- Enable npm caching and color output
- Restrict operations to main repository only
___
```mermaid
flowchart LR
A["Old CI Workflow"] --> B["Updated Actions v4"]
B --> C["Added Security Permissions"]
C --> D["Enabled NPM Cache"]
D --> E["Fork Protection"]
E --> F["Enhanced CI Workflow"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration …
> chore: improve CI

- __tests__/scripts.test.js
After #343 and this patch, tests pass on Windows native cmd:
```
Test Suites: 19 passed, 19 total
Tests:       6 skipped, 190 passed, 196 total
Snapshots:   0 total
Time:        32.208 s, estimated 33 s
Ran all test suites.
```
___
Tests
___
- Skip shell configuration tests on Windows platform
- Add conditional test execution utility function
- Improve cross-platform test compatibility
___
```mermaid
flowchart LR
A["Test Suite"] --> B["describeIf utility"]
B --> C["Platform Check"]
C --> D["Skip on Windows"]
C --> E["Run on Unix/Linux"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Tests</strong></td><td><table>
<tr>
<td>
<details> …
> chore(tests): skip shell tests on Windows

- __tests__/marshalls.snyk.test.js
- lib/helpers/packageRepoUtils.js
- lib/helpers/reportResults.js
- lib/marshalls/author.marshall.js
- lib/marshalls/license.marshall.js
- lib/marshalls/provenance.marshall.js
- lib/marshalls/signatures.marshall.js
- lib/marshalls/snyk.marshall.js
- lib/marshallsDecomissioned/readme.marshall.js
- scripts/build.js
Refs #346 
___
Other
___
- Remove unused variables and imports across multiple files
- Fix redundant conditions in conditional statements
- Convert synchronous to asynchronous function call
- Reorder imports for better organization
___
```mermaid
flowchart LR
A["Unused Variables"] --> B["Remove Imports"]
A --> C["Remove Variables"]
D["Redundant Conditions"] --> E["Simplify Logic"]
F["Async Issues"] --> G["Add Await"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Formatting</strong></td><td><details><summary>4 files</summary><table>
<tr>
<td><strong>marshalls.snyk.test.js</strong><dd><code>Remove unused imports and reorder</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> chore: fix some CodeQL issues

- .husky/commit-msg
- .husky/post-merge
- .husky/pre-commit
- .husky/pre-push
- eslint.config.js
- package-lock.json
- package.json
___
Other
___
- Upgrade ESLint to v9 with new flat config format
- Update major dependencies: npm-package-arg, pacote, commitlint, husky
- Simplify Husky hooks by removing shell boilerplate
- Disable husky prepare script temporarily
___
```mermaid
flowchart LR
A["Old ESLint v8"] --> B["New ESLint v9"]
C["Legacy .eslintrc"] --> D["Flat config eslint.config.js"]
E["Old Husky hooks"] --> F["Simplified Husky hooks"]
G["Old dependencies"] --> H["Updated dependencies"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>eslint.config.js</strong><dd><code>Add ESLint v9 flat configuration</code>&nbsp; &nbsp; …
> Fix: deps upgrade

- __tests__/marshalls.newBin.test.js
- __tests__/marshalls.version-maturity.test.js
- eslint.config.js
- lib/marshalls/age.marshall.js
- lib/marshalls/baseMarshall.js
- lib/marshalls/deprecation.marshall.js
- lib/marshalls/newbin.marshall.js
- lib/marshalls/provenance.marshall.js
- lib/marshalls/scripts.marshall.js
- lib/marshalls/version-maturity.marshall.js
Fixes #359 
___
Bug fix, Enhancement
___
- Refactor base marshall to support package alias version parsing
- Replace `getSemVer` with centralized `resolvePackageVersion` method
- Convert promise chains to async/await for better readability
- Fix version resolution for dist-tags and semver parsing
___
```mermaid
flowchart LR
A["BaseMarshall"] --> B["resolvePackageVersion()"]
B --> C["dist-tags resolution"]
B --> D["semver parsing"]
E["Marshall classes"] --> F["async/await refactor"]
F --> G["centralized version resolution"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>6 files</summary><table>
<tr> …
> fix: refactor base marshall to support package alias version parsing

- package-lock.json
- package.json
___
Other
___
- Remove unused `lodash` dependency from package.json
___
```mermaid
flowchart LR
A["package.json"] -- "remove" --> B["lodash dependency"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Dependencies</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>package.json</strong><dd><code>Remove lodash dependency</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
package.json
- Remove `lodash` dependency from the dependencies section
</details>
</td>
<td><a …
> fix: remove unused lodash dep
