bin/npq-hero.js, bin/npq.js, lib/cli.js, lib/cliCommons.js
=> fix(cli): shared set parsing for npm/yarn install options

package.json, yarn.lock
This PR introduces the use of lockfile-lint which aims to alleviate testing of lockfiles for trusted sources and protect against security concerns where malicious users may attempt to inject bad packages through lockfiles.
We lint for:
all resources must be served over HTTPS
allowed hosts are set for 'verdaccio', 'npm', and 'yarn' since all are used within the lockfile. This ensures the build doesn't fail, however I recommend that in later PRs we update those resources to include just one source, say verdaccio to not spread source of origin too much.
- add lockfile-lint dep
- use lockfile-lint in the lint run script
=> feat(lockfile-lint): 🎉 enforce lockfile security

__tests__/scripts.test.js, package.json, scripts/postinstall.js, scripts/preuninstall.js, scripts/scriptHelpers.js
implement #90
This PR adds post-install and pre-uninstall scripts to prompt the user to automatically add shell aliases for npq upon installation, and to automatically remove those aliases when uninstalling. Initially just supports bash and zsh.
https://github.com/lirantal/npq/issues/90
> When someone installs npq they would probably want to use it in an integrated manner with npm and yarn by aliasing it. (https://github.com/lirantal/npq/issues/90)
I've added integration tests for the two scripts, and unit tests for the shell detection code.
I haven't tested an interactive script like this one before, so I'm very happy to hear feedback here -- also on the fact that I couldn't quite get to the 90% coverage. The lines that aren't covered are related to file read/write error handling, and it …
=> feat(install scripts): add automatic shell alias installation

README.md, __tests__/scripts.test.js, scripts/postinstall.js, scripts/scriptHelpers.js
Fixes #154 .
I snuck in an additional fix: shell detection was not working properly in Windows because I had used '/' instead of `path.sep`. That's resolved now, and tested on Windows 10. Let me know if you'd like a separate PR for this instead.
#154 
Installs should work regardless of whether using npm or yarn!
Apologies for causing this bug in the first place, but glad it's fixed now :)
I added a test verifying that the install script doesn't run in yarn. Of course, the added code in this PR broke several tests when running `yarn test` rather than `npm run test`! I worked around that.
I'm not super happy about this conditional -- it feels too fragile that tests can pass in `npm` but fail in `yarn` without explicitly working around that. However, I can't think of a cleaner way to handle …
=> fix(install scripts): don't run install script in yarn

lib/cliCommons.js, package.json, yarn.lock
Introducing library [npm-package-arg](https://www.npmjs.com/package/npm-package-arg) that parse the alias input name of the package and return us various information about the package (there is a name that we need)
[152](https://github.com/lirantal/npq/issues/152)
So this should work fine by parsing properly the ```jquery@2``` as a package name
```npq install jquery2@npm:jquery@2```
Tested with various examples of alias package
=> fix: npq doesn't support the npm alias convention #152

lib/cliCommons.js
Adding support for getting names of n arguments, not just the first argument
We will still have an issue if we only cover the first argument, that's why we need to cover all arguments example
npq install express jquery2@npm:jquery@2
=> fix: npq doesn't support the npm alias convention #152 n packages cover

lib/marshalls/license.marshall.js
README was being checked in LICENSE marshalling resulting in duplicate "package has no README file
available" messages
Fixing erroneous (I suspect copy-pasted) code where functionality conflicted with naming (i.e. `getReadmeInfo` used in `license.marshall.js`.
Existing tests all pass. While there was already a test for `getLicenseInfo`, the method itself was never actually called.
=> fix(marshalls): fix readme/license confusion

lib/marshalls/snyk.marshall.js
Replaced the `encodeURIComponent` function used on the package name and the package version to build queried Snyk URLs with `encodeURI` on the whole built URL, to apply changes like "@" –> `%40` and "/" –> `%2F` only on query params that are not part of the URL path.
Fixes #172.
Solves the `Unable to query vulnerabilities for packages` error when trying to install packages whose name includes characters such as "@" and "/".
I ran `npm run test` and manually tried to install `@nestjs/cli` with `node npq/bin/npq-hero.js install @nestjs/cli@latest --global` to make sure that it solved the issue. I tried to see if I could add a test for this use case but I think you don't test individual marshalls.
- N/A I have updated the documentation (if required).
=> Replace encodeURIComponent with encodeURI for Snyk URLs

__tests__/marshalls.repo.test.js, __tests__/packageRepoUtils.test.js, lib/helpers/packageRepoUtils.js, lib/marshalls/repo.marshall.js, lib/marshalls/snyk.marshall.js, package-lock.json, package.json
replace `axios` to `node-fetch`
I'm trying to replace `axios` with `node-fetch`.
`axios` is now used at
- `repo.marshall.js`
- `packageRepoUtils.js`
- `snyk.marshall.js`
I've already replaced all and rewrite tests.
https://github.com/lirantal/npq/issues/169
https://github.com/lirantal/npq/issues/169
>Currently all calls are being done with the the axios npm package which I'd like to replace for a lower dependency footprint.
Using `jest.mock('node-fetch')` instead of `jest.mock('axios')`
=> perf: replace axios to node-fetch

__tests__/packageRepoUtils.test.js, lib/helpers/packageRepoUtils.js, lib/marshalls/snyk.marshall.js
Use [JSON response interface of fetch (and node-fetch)](https://www.npmjs.com/package/node-fetch#json)
TBH, I don't understand how this is working for you guys...
#176 176
This application did not work on my machine at all
Ran on my machine with success for multiple packages
| Before | After
| - | -
| ![](https://user-images.githubusercontent.com/516342/100932340-64a2fd80-34f4-11eb-8be6-feffea36f6cb.png) | ![](https://user-images.githubusercontent.com/516342/100932378-74badd00-34f4-11eb-9192-2ca519b98cd5.png)
=> fix: use fetch json interface

__tests__/marshalls.repo.test.js, lib/marshalls/repo.marshall.js
The URL of git repos takes the form of `git+https://` which is an invalid URL as is to access on the web, which caused repo URL checks to fail
Updated relevant tests and fixed mocks usage within tests.
=> Fix issue with git urls being unsupported for repo 

__tests__/scripts.test.js, scripts/postinstall.js, scripts/scriptHelpers.js
In npm v7 the `postinstall` script longer accepts user input and does not show any messages to the user.
this make npq fails at installation in npm v7. to solve this I disabled the prompt in npm v7
Fixes #185 
had a problem with installing npq in npm v7 and wanted to solve it.
Added automatic tests to the project. 
run the project on windows and ubuntu machines with both npm v6, npm v7, and yarn
=> Disabled `postinstall` Prompt In NPM v7

README.md
Add descriptions for the `author` and `repo` marshalls to the README.
I was looking for a way to disable the `author` warning and noticed it's supported but not documented.
Running `MARSHALL_DISABLE_AUTHOR=1 npm i package-without-author`.
<details>
<summary>Screenshot</summary>
</details>
=> docs: add missing marshalls to README

README.md
Fixes the following:
* The link at https://www.javascriptjanuary.com/blog/open-source-from-heaven-modules-from-hell is no longer operational as the website is down so removing it
* Updating the malicious modules entry from medium.com to lirantal.com
Fixes #232
=> docs: fix out-dated links

.github/workflows/main.yml
Update workflow to run tests with up to date Node.js version matrix: 16 and 18.
=> build: update build matrix for current Node.js versions

__tests__/marshalls.expiredDomains.test.js, lib/marshalls/expiredDomains.marshall.js, package.json
Fixes #208 
Introduces new marshall for expired domains, as sourced from the signal for weak npm packages in the research titled `What are Weak Links in the npm Supply Chain?` - we should be able to find and match packages which their maintainers have expired domains and warn on install.
=> feat: add support for expired domains marshall

__tests__/marshalls.expiredDomains.test.js
No need to mock HTTP calls, removing unnecessary mocking of modules using `jest.mock`
=> test: remove unnecessary module mocking

lib/marshalls/snyk.marshall.js
Fixed accidental snyk Marshall disabled
=> fix: snyk tests always true

lib/marshalls/author.marshall.js
This new revamp about checking the author is changed to be geared towards supply chain security signals of package hijacking or package compromise.
What do we check?
1. Who is the user who published the package? in the pakument's `_npmUser` field
2. Is this the first time we see this user publishing a package? If so, halt and report.
3. Start from first version to latest version and check if they published the package before. If they did, and the difference between this published version date and first is more than 30 days then halt and report.
=> feat: revamp package author check for potential package compromise

lib/marshalls/typosquatting.marshall.js
Don't report on the package if it is found in the top popular packages dataset
=> fix: dont report on the package if it is popular

lib/cliCommons.js
Fix #300 
Add support for `--save` flag and others that are supported by npm cli
=> fix: support for --save flag and others that are supported by npm cli

lib/marshalls/author.marshall.js
if a package had a below 30 days time diff between author first relases to the version being grabbed, but was 8 years old on the registry then the alert would still show up.
this was fixed with a 45 days window from the released version and up to the current date as a more sane check
=> fix: author marshall reported date diff for very old package releases

lib/marshalls/age.marshall.js
age marshall checks if package version downloaded is more than 365 days old
=> feat: age marshall check unmaintained packages
